In [17]:
import numpy as np
a1=np.array([10,20,30,40])
a2=np.array([50,60,70,80])
L1=[10,20,30,40]
L2=[50,60,70,80]
a1,a2,L1,L2

(array([10, 20, 30, 40]),
 array([50, 60, 70, 80]),
 [10, 20, 30, 40],
 [50, 60, 70, 80])

## Differences in between python list and numpy array

In [18]:
# + operator
a1+a2#adds Respective elements

array([ 60,  80, 100, 120])

In [20]:
L1+L2#concatenate 2 lists

[10, 20, 30, 40, 50, 60, 70, 80]

In [22]:
# * operator
a1*a2#multiplies all the elements

array([ 500, 1200, 2100, 3200])

In [23]:
L1*L2

TypeError: can't multiply sequence by non-int of type 'list'

In [24]:
a1*2#multiplies with 2 to all the elements of a1

array([20, 40, 60, 80])

In [25]:
L1*2#Replicates list elements with 2

[10, 20, 30, 40, 10, 20, 30, 40]

In [26]:
a1**2 #squares the elements a1

array([ 100,  400,  900, 1600], dtype=int32)

In [27]:
L1**2#Error

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [5]:
a2=np.array([[10,20,30],[40,50,60],[70,80,90]])
a2.shape

(3, 3)

In [9]:
np.zeros(10,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [11]:
z=np.zeros((3,3),dtype='int64')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [12]:
on=np.ones((4,4),dtype='int64')
on

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [28]:
tw=np.ones((3,3),dtype='int64')*2
tw

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [29]:
th=np.ones((3,3),dtype='int64')*3
th

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int64)

In [32]:
ey=np.eye(7,dtype='int64')#Identity Matrix
ey

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [34]:
for i in range(1,11,100):
    print(i)

1


In [51]:
L=np.linspace(1,10,100)
len(L),L

(100,
 array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
         1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
         2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
         3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
         4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
         5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
         6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [52]:
np.linspace(1.3,10.3,30)

array([ 1.3       ,  1.61034483,  1.92068966,  2.23103448,  2.54137931,
        2.85172414,  3.16206897,  3.47241379,  3.78275862,  4.09310345,
        4.40344828,  4.7137931 ,  5.02413793,  5.33448276,  5.64482759,
        5.95517241,  6.26551724,  6.57586207,  6.8862069 ,  7.19655172,
        7.50689655,  7.81724138,  8.12758621,  8.43793103,  8.74827586,
        9.05862069,  9.36896552,  9.67931034,  9.98965517, 10.3       ])

In [35]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [39]:
np.arange(1.3,11.3,2)#Note: np.arange allows us to use floating point numbers

array([1.3, 3.3, 5.3, 7.3, 9.3])

In [54]:
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [55]:
np.random.rand(4,5)#only +ve value in the range(0,1)

array([[0.00726736, 0.9851591 , 0.43065629, 0.65808431, 0.96299652],
       [0.05749488, 0.41243745, 0.12955752, 0.77443407, 0.46238381],
       [0.66681704, 0.97865982, 0.48813852, 0.6426254 , 0.65737003],
       [0.78708456, 0.83510423, 0.86198065, 0.87385771, 0.11337796]])

In [56]:
np.random.randn(4,5)#it includes +ve and -ve values in the range(0,1) with median

array([[ 1.93918506,  0.22605252,  2.10371675, -0.60434232, -0.25661201],
       [-0.3829644 , -1.50424507, -0.5117381 ,  1.42301267, -0.61875095],
       [-0.43608763, -0.13221427,  0.76106518,  0.29222323,  0.17197145],
       [ 0.3846008 , -0.31874735,  0.24247035, -0.17244492, -0.24837579]])

In [57]:
np.random.rand(6,7)*100

array([[28.4181113 , 23.33210911, 88.40252262, 87.63702715, 65.08491413,
        12.33952611, 87.32442627],
       [87.64935165, 57.98503207, 19.35240971, 27.19862165, 38.95983069,
        14.90015225, 16.66115844],
       [12.04033485, 14.498838  , 17.27133423, 33.54641037,  7.91915618,
        83.81230299,  4.65224691],
       [31.98445377, 25.76799408, 53.64261601, 80.66475384, 77.6361631 ,
        19.39314305, 39.58806824],
       [31.08434182, 47.45322171, 51.70540448, 60.18688835, 59.3930365 ,
        80.68995467, 71.68399073],
       [ 1.19757827, 64.76323298, 27.24815795, 19.13488409, 80.17991862,
        84.70743557, 48.84645745]])

In [58]:
L=np.random.rand(3,3)
L

array([[0.59638548, 0.56989726, 0.06642505],
       [0.65983796, 0.56786403, 0.67869565],
       [0.61026839, 0.80797222, 0.1378889 ]])

In [59]:
L*100

array([[59.63854807, 56.98972602,  6.64250462],
       [65.98379597, 56.78640263, 67.86956542],
       [61.0268388 , 80.79722244, 13.78889043]])

In [41]:
h=np.random.randint(60,130,size=(5,5))
h

array([[106, 122,  70, 129,  75],
       [ 66,  69,  83, 123,  80],
       [112,  89, 101, 114,  87],
       [ 72, 122,  64,  69,  87],
       [ 76,  82,  94, 107,  62]])

In [43]:
data=np.random.randint(3,30,size=(5,5))
data

array([[18, 25, 25, 28, 17],
       [29, 10, 29,  4, 11],
       [23, 21, 10, 13, 16],
       [20, 26, 11,  3,  9],
       [29, 12, 13, 25, 20]])

In [44]:
data.size#product of row*cols

25

In [45]:
data.dtype#returns data type of elements

dtype('int32')

In [48]:
data=data.astype('int64')#astype=>It converts elements to given datatype

In [49]:
data.dtype

dtype('int64')

In [51]:
data.astype('float64')

array([[18., 25., 25., 28., 17.],
       [29., 10., 29.,  4., 11.],
       [23., 21., 10., 13., 16.],
       [20., 26., 11.,  3.,  9.],
       [29., 12., 13., 25., 20.]])

In [53]:
lt=data.tolist()
lt

[[18, 25, 25, 28, 17],
 [29, 10, 29, 4, 11],
 [23, 21, 10, 13, 16],
 [20, 26, 11, 3, 9],
 [29, 12, 13, 25, 20]]

In [54]:
np.info(data)

class:  ndarray
shape:  (5, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1793ef82e00
byteorder:  little
byteswap:  False
type: int64


In [68]:
data=data.astype('float')
data

array([[24.,  7.,  8., 24.,  3.],
       [ 4., 29., 23., 17.,  7.],
       [26., 13.,  3.,  3., 11.],
       [ 9.,  5.,  3., 25., 10.],
       [ 8., 13.,  8.,  6., 23.]])

In [69]:
data.view('int64')

array([[4627448617123184640, 4619567317775286272, 4620693217682128896,
        4627448617123184640, 4613937818241073152],
       [4616189618054758400, 4628855992006737920, 4627167142146473984,
        4625478292286210048, 4619567317775286272],
       [4628011567076605952, 4623507967449235456, 4613937818241073152,
        4613937818241073152, 4622382067542392832],
       [4621256167635550208, 4617315517961601024, 4613937818241073152,
        4627730092099895296, 4621819117588971520],
       [4620693217682128896, 4623507967449235456, 4620693217682128896,
        4618441417868443648, 4627167142146473984]], dtype=int64)

In [55]:
data=data.astype('int64')
data

array([[18, 25, 25, 28, 17],
       [29, 10, 29,  4, 11],
       [23, 21, 10, 13, 16],
       [20, 26, 11,  3,  9],
       [29, 12, 13, 25, 20]], dtype=int64)

In [56]:
data.sort()#row-wise sorting

In [57]:
data

array([[17, 18, 25, 25, 28],
       [ 4, 10, 11, 29, 29],
       [10, 13, 16, 21, 23],
       [ 3,  9, 11, 20, 26],
       [12, 13, 20, 25, 29]], dtype=int64)

In [58]:
data.sort(axis=0)#column-wise sorting
data

array([[ 3,  9, 11, 20, 23],
       [ 4, 10, 11, 21, 26],
       [10, 13, 16, 25, 28],
       [12, 13, 20, 25, 29],
       [17, 18, 25, 29, 29]], dtype=int64)

In [60]:
data.flatten()# converting 2D array to 1D

array([ 3,  9, 11, 20, 23,  4, 10, 11, 21, 26, 10, 13, 16, 25, 28, 12, 13,
       20, 25, 29, 17, 18, 25, 29, 29], dtype=int64)

In [61]:
data.T#Transpose

array([[ 3,  4, 10, 12, 17],
       [ 9, 10, 13, 13, 18],
       [11, 11, 16, 20, 25],
       [20, 21, 25, 25, 29],
       [23, 26, 28, 29, 29]], dtype=int64)

In [62]:
data

array([[ 3,  9, 11, 20, 23],
       [ 4, 10, 11, 21, 26],
       [10, 13, 16, 25, 28],
       [12, 13, 20, 25, 29],
       [17, 18, 25, 29, 29]], dtype=int64)

In [63]:
ex=np.random.randint(10,30,size=(3,4))
ex

array([[22, 19, 25, 11],
       [24, 22, 13, 18],
       [10, 21, 29, 12]])

In [64]:
ex.reshape(4,3)

array([[22, 19, 25],
       [11, 24, 22],
       [13, 18, 10],
       [21, 29, 12]])

In [65]:
ex.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [80]:
ex.reshape(2,6)

array([[27, 24, 23, 16, 20, 27],
       [25, 23, 28, 25, 28, 18]])

In [66]:
np.resize(ex,(4,4))

array([[22, 19, 25, 11],
       [24, 22, 13, 18],
       [10, 21, 29, 12],
       [22, 19, 25, 11]])

In [67]:
np.resize(data,(5,6))

array([[ 3,  9, 11, 20, 23,  4],
       [10, 11, 21, 26, 10, 13],
       [16, 25, 28, 12, 13, 20],
       [25, 29, 17, 18, 25, 29],
       [29,  3,  9, 11, 20, 23]], dtype=int64)

In [83]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [84]:
arr=np.append(arr,10)
arr

array([ 1,  2,  3, 10])

In [85]:
ex

array([[27, 24, 23, 16],
       [20, 27, 25, 23],
       [28, 25, 28, 18]])

In [86]:
np.delete(ex,2,axis=1)#deletes col 2 from array

array([[27, 24, 16],
       [20, 27, 23],
       [28, 25, 18]])

In [87]:
np.delete(ex,2,axis=0)#deletes row 2 from array

array([[27, 24, 23, 16],
       [20, 27, 25, 23]])

In [88]:
data

array([[ 3,  3,  8, 10, 23],
       [ 3,  5,  8, 13, 24],
       [ 3,  7,  9, 13, 25],
       [ 4,  7, 11, 23, 26],
       [ 6,  8, 17, 24, 29]], dtype=int64)

In [89]:
h

array([[125,  69, 121,  80,  61],
       [ 89,  87, 112,  82,  79],
       [ 74, 115, 122,  71,  82],
       [ 98,  77, 115,  77,  72],
       [118,  81, 100, 123,  90]])

In [90]:
np.concatenate((data,h),axis=0) #row-wise 

array([[  3,   3,   8,  10,  23],
       [  3,   5,   8,  13,  24],
       [  3,   7,   9,  13,  25],
       [  4,   7,  11,  23,  26],
       [  6,   8,  17,  24,  29],
       [125,  69, 121,  80,  61],
       [ 89,  87, 112,  82,  79],
       [ 74, 115, 122,  71,  82],
       [ 98,  77, 115,  77,  72],
       [118,  81, 100, 123,  90]], dtype=int64)

In [91]:
np.concatenate((data,h),axis=1)#col-wise

array([[  3,   3,   8,  10,  23, 125,  69, 121,  80,  61],
       [  3,   5,   8,  13,  24,  89,  87, 112,  82,  79],
       [  3,   7,   9,  13,  25,  74, 115, 122,  71,  82],
       [  4,   7,  11,  23,  26,  98,  77, 115,  77,  72],
       [  6,   8,  17,  24,  29, 118,  81, 100, 123,  90]], dtype=int64)

In [92]:
np.split(h,5)#row-wise split

[array([[125,  69, 121,  80,  61]]),
 array([[ 89,  87, 112,  82,  79]]),
 array([[ 74, 115, 122,  71,  82]]),
 array([[ 98,  77, 115,  77,  72]]),
 array([[118,  81, 100, 123,  90]])]

In [93]:
np.hsplit(h,5)#col-wise split

[array([[125],
        [ 89],
        [ 74],
        [ 98],
        [118]]),
 array([[ 69],
        [ 87],
        [115],
        [ 77],
        [ 81]]),
 array([[121],
        [112],
        [122],
        [115],
        [100]]),
 array([[ 80],
        [ 82],
        [ 71],
        [ 77],
        [123]]),
 array([[61],
        [79],
        [82],
        [72],
        [90]])]

In [94]:
h

array([[125,  69, 121,  80,  61],
       [ 89,  87, 112,  82,  79],
       [ 74, 115, 122,  71,  82],
       [ 98,  77, 115,  77,  72],
       [118,  81, 100, 123,  90]])

In [95]:
h[0][2]

121

In [96]:
h[0,2]

121

In [97]:
#arr[rowindex,colindex]
h[::2, :]

array([[125,  69, 121,  80,  61],
       [ 74, 115, 122,  71,  82],
       [118,  81, 100, 123,  90]])

In [98]:
h[1::2, ::2]

array([[ 89, 112,  79],
       [ 98, 115,  72]])

In [99]:
h>70

array([[ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [100]:
h[h>70]

array([125, 121,  80,  89,  87, 112,  82,  79,  74, 115, 122,  71,  82,
        98,  77, 115,  77,  72, 118,  81, 100, 123,  90])