In [1]:
import numpy as np
a1=np.array([10,20,30,40])
a2=np.array([50,60,70,80])
L1=[10,20,30,40]
L2=[50,60,70,80]
a1,a2,L1,L2

(array([10, 20, 30, 40]),
 array([50, 60, 70, 80]),
 [10, 20, 30, 40],
 [50, 60, 70, 80])

In [2]:
# + operator
a1+a2#adds Respective elements

array([ 60,  80, 100, 120])

In [3]:
L1+L2#concatenate 2 lists

[10, 20, 30, 40, 50, 60, 70, 80]

In [4]:
# * operator
a1*a2#multiplies all the elements

array([ 500, 1200, 2100, 3200])

In [5]:
L1*L2

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
a1*2#multiplies with 2 to all the elements of a1

array([20, 40, 60, 80])

In [7]:
L1*2#Replicates list elements with 2

[10, 20, 30, 40, 10, 20, 30, 40]

In [8]:
a1**2 #squares the elements a1

array([ 100,  400,  900, 1600], dtype=int32)

In [9]:
L1**2#Error

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
a2=np.array([[10,20,30],[40,50,60],[70,80,90]])
a2.shape

(3, 3)

In [11]:
np.zeros(10,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
z=np.zeros((3,3),dtype='int64')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [13]:
on=np.ones((4,4),dtype='int64')
on

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [14]:
tw=np.ones((3,3),dtype='int64')*2
tw

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [15]:
th=np.ones((3,3),dtype='int64')*3
th

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int64)

In [16]:
ey=np.eye(7,dtype='int64')#Identity Matrix
ey

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [17]:
for i in range(1,11,100):
    print(i)

1


In [18]:
L=np.linspace(1,10,100)
len(L),L

(100,
 array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
         1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
         2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
         3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
         4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
         5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
         6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [19]:
np.linspace(1.3,10.3,30)

array([ 1.3       ,  1.61034483,  1.92068966,  2.23103448,  2.54137931,
        2.85172414,  3.16206897,  3.47241379,  3.78275862,  4.09310345,
        4.40344828,  4.7137931 ,  5.02413793,  5.33448276,  5.64482759,
        5.95517241,  6.26551724,  6.57586207,  6.8862069 ,  7.19655172,
        7.50689655,  7.81724138,  8.12758621,  8.43793103,  8.74827586,
        9.05862069,  9.36896552,  9.67931034,  9.98965517, 10.3       ])

In [20]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [22]:
np.arange(1.3,11.3,2)#Note: np.arange allows us to use floating point numbers

array([1.3, 3.3, 5.3, 7.3, 9.3])

In [23]:
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [24]:
np.random.rand(4,5)#only +ve value in the range(0,1)

array([[0.38738084, 0.62434624, 0.99946261, 0.56364937, 0.32647713],
       [0.59258217, 0.41487705, 0.21170584, 0.29405224, 0.84663827],
       [0.17170815, 0.67617578, 0.50759748, 0.10318332, 0.28507273],
       [0.79037067, 0.98760017, 0.51719539, 0.01039569, 0.3536571 ]])

In [25]:
np.random.randn(4,5)#it includes +ve and -ve values in the range(0,1) with median

array([[-1.69320842, -0.56500464, -0.02389776, -0.63724725, -0.0707476 ],
       [-1.06546449,  0.39496164, -2.42454369, -0.86569912, -0.13486406],
       [-0.86611562,  2.01724566, -0.49651848, -0.17152796, -0.52585288],
       [-0.0059324 , -0.333719  , -0.76514237,  0.12344019,  0.3355158 ]])

In [26]:
np.random.rand(6,7)*100

array([[99.78705104, 18.12077461,  2.26542874, 92.99481993, 48.84450837,
        43.07658332, 85.6631091 ],
       [90.53120628, 75.63288119, 64.16536689, 24.49538321, 17.98158248,
        76.36639516, 35.25995765],
       [76.15306352, 36.5720813 , 75.38576794, 49.2872923 ,  6.19430649,
        86.71300777, 34.65250029],
       [50.22995243, 26.20582787, 81.83817165, 54.84920995,  3.07154012,
        19.46349235,  4.49891243],
       [40.69783231, 95.89474083, 98.3961243 , 21.12554875, 81.20904224,
        64.56571989, 53.75122861],
       [53.41738701, 69.88670888, 89.67240053,  6.33111725, 36.21739231,
        19.21495417, 19.21207463]])

In [27]:
L=np.random.rand(3,3)
L

array([[0.00767009, 0.54787904, 0.97251035],
       [0.71290999, 0.770149  , 0.12327734],
       [0.17934054, 0.48455216, 0.0506639 ]])

In [28]:
L*100

array([[ 0.76700877, 54.78790443, 97.25103528],
       [71.2909993 , 77.01489961, 12.32773407],
       [17.93405391, 48.45521646,  5.06638957]])

In [29]:
h=np.random.randint(60,130,size=(5,5))
h

array([[ 84,  79, 106, 103, 115],
       [ 66,  87,  94,  70,  88],
       [ 77, 103,  91, 112, 108],
       [ 97, 115,  81,  92, 110],
       [ 72,  97, 118, 114,  80]])

In [30]:
data=np.random.randint(3,30,size=(5,5))
data

array([[ 4, 21,  7, 25, 23],
       [ 6, 25, 28, 29,  6],
       [23, 10, 23, 12, 28],
       [29, 26, 11, 18,  3],
       [25, 28, 25, 15,  8]])

In [31]:
data.size#product of row*cols

25

In [32]:
data.dtype#returns data type of elements

dtype('int32')

In [33]:
data=data.astype('int64')#astype=>It converts elements to given datatype

In [34]:
data.dtype

dtype('int64')

In [35]:
data.astype('float64')

array([[ 4., 21.,  7., 25., 23.],
       [ 6., 25., 28., 29.,  6.],
       [23., 10., 23., 12., 28.],
       [29., 26., 11., 18.,  3.],
       [25., 28., 25., 15.,  8.]])

In [36]:
lt=data.tolist()
lt

[[4, 21, 7, 25, 23],
 [6, 25, 28, 29, 6],
 [23, 10, 23, 12, 28],
 [29, 26, 11, 18, 3],
 [25, 28, 25, 15, 8]]

In [37]:
np.info(data)

class:  ndarray
shape:  (5, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2a403e9f820
byteorder:  little
byteswap:  False
type: int64


In [38]:
data=data.astype('float')
data

array([[ 4., 21.,  7., 25., 23.],
       [ 6., 25., 28., 29.,  6.],
       [23., 10., 23., 12., 28.],
       [29., 26., 11., 18.,  3.],
       [25., 28., 25., 15.,  8.]])

In [39]:
data.view('int64')

array([[4616189618054758400, 4626604192193052672, 4619567317775286272,
        4627730092099895296, 4627167142146473984],
       [4618441417868443648, 4627730092099895296, 4628574517030027264,
        4628855992006737920, 4618441417868443648],
       [4627167142146473984, 4621819117588971520, 4627167142146473984,
        4622945017495814144, 4628574517030027264],
       [4628855992006737920, 4628011567076605952, 4622382067542392832,
        4625759767262920704, 4613937818241073152],
       [4627730092099895296, 4628574517030027264, 4627730092099895296,
        4624633867356078080, 4620693217682128896]], dtype=int64)

In [40]:
data=data.astype('int64')
data

array([[ 4, 21,  7, 25, 23],
       [ 6, 25, 28, 29,  6],
       [23, 10, 23, 12, 28],
       [29, 26, 11, 18,  3],
       [25, 28, 25, 15,  8]], dtype=int64)

In [41]:
data.sort()#row-wise sorting

In [42]:
data

array([[ 4,  7, 21, 23, 25],
       [ 6,  6, 25, 28, 29],
       [10, 12, 23, 23, 28],
       [ 3, 11, 18, 26, 29],
       [ 8, 15, 25, 25, 28]], dtype=int64)

In [43]:
data.sort(axis=0)#column-wise sorting
data

array([[ 3,  6, 18, 23, 25],
       [ 4,  7, 21, 23, 28],
       [ 6, 11, 23, 25, 28],
       [ 8, 12, 25, 26, 29],
       [10, 15, 25, 28, 29]], dtype=int64)

In [44]:
data.flatten()# converting 2D array to 1D

array([ 3,  6, 18, 23, 25,  4,  7, 21, 23, 28,  6, 11, 23, 25, 28,  8, 12,
       25, 26, 29, 10, 15, 25, 28, 29], dtype=int64)

In [45]:
data.T#Transpose

array([[ 3,  4,  6,  8, 10],
       [ 6,  7, 11, 12, 15],
       [18, 21, 23, 25, 25],
       [23, 23, 25, 26, 28],
       [25, 28, 28, 29, 29]], dtype=int64)

In [46]:
data

array([[ 3,  6, 18, 23, 25],
       [ 4,  7, 21, 23, 28],
       [ 6, 11, 23, 25, 28],
       [ 8, 12, 25, 26, 29],
       [10, 15, 25, 28, 29]], dtype=int64)

In [47]:
ex=np.random.randint(10,30,size=(3,4))
ex

array([[16, 11, 21, 26],
       [20, 17, 22, 29],
       [20, 29, 28, 10]])

In [48]:
ex.reshape(4,3)

array([[16, 11, 21],
       [26, 20, 17],
       [22, 29, 20],
       [29, 28, 10]])

In [49]:
ex.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [50]:
ex.reshape(2,6)

array([[16, 11, 21, 26, 20, 17],
       [22, 29, 20, 29, 28, 10]])

In [51]:
np.resize(ex,(4,4))

array([[16, 11, 21, 26],
       [20, 17, 22, 29],
       [20, 29, 28, 10],
       [16, 11, 21, 26]])

In [52]:
np.resize(data,(5,6))

array([[ 3,  6, 18, 23, 25,  4],
       [ 7, 21, 23, 28,  6, 11],
       [23, 25, 28,  8, 12, 25],
       [26, 29, 10, 15, 25, 28],
       [29,  3,  6, 18, 23, 25]], dtype=int64)

In [53]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [54]:
arr=np.append(arr,10)
arr

array([ 1,  2,  3, 10])

In [55]:
ex

array([[16, 11, 21, 26],
       [20, 17, 22, 29],
       [20, 29, 28, 10]])

In [56]:
np.delete(ex,2,axis=1)#deletes col 2 from array

array([[16, 11, 26],
       [20, 17, 29],
       [20, 29, 10]])

In [57]:
np.delete(ex,2,axis=0)#deletes row 2 from array

array([[16, 11, 21, 26],
       [20, 17, 22, 29]])

In [58]:
data

array([[ 3,  6, 18, 23, 25],
       [ 4,  7, 21, 23, 28],
       [ 6, 11, 23, 25, 28],
       [ 8, 12, 25, 26, 29],
       [10, 15, 25, 28, 29]], dtype=int64)

In [59]:
h

array([[ 84,  79, 106, 103, 115],
       [ 66,  87,  94,  70,  88],
       [ 77, 103,  91, 112, 108],
       [ 97, 115,  81,  92, 110],
       [ 72,  97, 118, 114,  80]])

In [61]:
np.concatenate((data,h),axis=0) #row-wise 

array([[  3,   6,  18,  23,  25],
       [  4,   7,  21,  23,  28],
       [  6,  11,  23,  25,  28],
       [  8,  12,  25,  26,  29],
       [ 10,  15,  25,  28,  29],
       [ 84,  79, 106, 103, 115],
       [ 66,  87,  94,  70,  88],
       [ 77, 103,  91, 112, 108],
       [ 97, 115,  81,  92, 110],
       [ 72,  97, 118, 114,  80]], dtype=int64)

In [62]:
np.concatenate((data,h),axis=1)#col-wise

array([[  3,   6,  18,  23,  25,  84,  79, 106, 103, 115],
       [  4,   7,  21,  23,  28,  66,  87,  94,  70,  88],
       [  6,  11,  23,  25,  28,  77, 103,  91, 112, 108],
       [  8,  12,  25,  26,  29,  97, 115,  81,  92, 110],
       [ 10,  15,  25,  28,  29,  72,  97, 118, 114,  80]], dtype=int64)

In [63]:
np.split(h,5)#row-wise split

[array([[ 84,  79, 106, 103, 115]]),
 array([[66, 87, 94, 70, 88]]),
 array([[ 77, 103,  91, 112, 108]]),
 array([[ 97, 115,  81,  92, 110]]),
 array([[ 72,  97, 118, 114,  80]])]

In [64]:
np.hsplit(h,5)#col-wise split

[array([[84],
        [66],
        [77],
        [97],
        [72]]),
 array([[ 79],
        [ 87],
        [103],
        [115],
        [ 97]]),
 array([[106],
        [ 94],
        [ 91],
        [ 81],
        [118]]),
 array([[103],
        [ 70],
        [112],
        [ 92],
        [114]]),
 array([[115],
        [ 88],
        [108],
        [110],
        [ 80]])]

In [65]:
h

array([[ 84,  79, 106, 103, 115],
       [ 66,  87,  94,  70,  88],
       [ 77, 103,  91, 112, 108],
       [ 97, 115,  81,  92, 110],
       [ 72,  97, 118, 114,  80]])

In [66]:
h[0][2]

106

In [67]:
h[0,2]

106

In [68]:
#arr[rowindex,colindex]
h[::2, :]

array([[ 84,  79, 106, 103, 115],
       [ 77, 103,  91, 112, 108],
       [ 72,  97, 118, 114,  80]])

In [69]:
h[1::2, ::2]

array([[ 66,  94,  88],
       [ 97,  81, 110]])

In [70]:
h>70

array([[ True,  True,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [71]:
h[h>70]

array([ 84,  79, 106, 103, 115,  87,  94,  88,  77, 103,  91, 112, 108,
        97, 115,  81,  92, 110,  72,  97, 118, 114,  80])